"""empty message

Revision ID: d2be62d9a252
Revises: 6e4288db8f5e
Create Date: 2020-07-03 09:16:10.151867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2be62d9a252'
down_revision = '6e4288db8f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_grid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('list', sa.Column('list_grid_id', sa.Integer(), nullable=True))
    op.add_column('list', sa.Column('position', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'list', 'list_grid', ['list_grid_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'list', type_='foreignkey')
    op.drop_column('list', 'position')
    op.drop_column('list', 'list_grid_id')
    op.drop_table('list_grid')
    # ### end Alembic commands ###
